on: [push, pull_request]

name: R-CMD-check

jobs:
  R-CMD-check:
    if: "! contains(github.event.head_commit.message, '[ci skip]')"

    timeout-minutes: 45

    runs-on: ${{ matrix.config.os }}

    name: r-${{ matrix.config.r }} ${{ matrix.config.testsets }} (${{ matrix.config.os }})

    strategy:
      fail-fast: false
      matrix:
        config:
#          - {os: windows-latest, r: 'devel'    }
          - {os: windows-latest, r: 'release'  }
#          - {os: windows-latest, r: 'oldrel'   }
#          - {os: macOS-latest,   r: 'devel'    }
#          - {os: macOS-latest,   r: 'release'  }
          - {os: macOS-latest,   r: 'oldrel'   }
#          - {os: ubuntu-latest,  r: 'devel'    }
          - {os: ubuntu-latest,  r: 'release', testsets: caret }
          - {os: ubuntu-latest,  r: 'release', testsets: foreach }
          - {os: ubuntu-latest,  r: 'release', testsets: glmnet }
          - {os: ubuntu-latest,  r: 'release', testsets: plyr }
          - {os: ubuntu-latest,  r: 'release', testsets: TSP }

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      ## R CMD check
      _R_CHECK_CRAN_INCOMING_: false
      _R_CHECK_LENGTH_1_CONDITION_: true
      _R_CHECK_LENGTH_1_LOGIC2_: true
      _R_CHECK_MATRIX_DATA_: true
      _R_CHECK_SUGGESTS_ONLY_: true
      _R_CHECK_THINGS_IN_TEMP_DIR_: true
      ## Specific to 'rcmdcheck'
      RCMDCHECK_ERROR_ON: note
      ## Specific to futures
#      R_FUTURE_RNG_ONMISUSE: error
      ## Specific to this package
      _R_CHECK_TESTSETS_: ${{ matrix.config.testsets }}

    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}
          http-user-agent: ${{ matrix.config.http-user-agent }}
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::rcmdcheck any::remotes any::BiocManager
          needs: check

      - name: Install dependencies
        run: |
          ## We have to manually install dependencies on Bioconductor 
          BiocManager::install("BiocParallel")
          ## Dependencies of dependencies that are on Bioconductor 
          BiocManager::install(c("Biobase"))
          remotes::install_deps(dependencies = TRUE)
          install.packages(".", repos = NULL, type = "source") ## needed for parallel tests
        shell: Rscript {0}

      - name: Session info
        run: |
          options(width = 100)
          parallelly::availableCores(which = "all")
          sapply(c(physical_cores = FALSE, logical_cores = TRUE), parallel::detectCores)
          if (require(RhpcBLASctl, quietly=TRUE)) c(get_num_procs = get_num_procs(), get_num_cores = get_num_cores(), blas_get_num_procs = blas_get_num_procs(), omp_get_num_procs = omp_get_num_procs(), omp_get_max_threads = omp_get_max_threads())
          capabilities()
          pkgs <- installed.packages()[, "Package"]
          sessioninfo::session_info(pkgs, include_base = TRUE)
          ## Verify LANGUAGE settings by generating a translatable error
          cat(sprintf("LANGUAGE=%s\n", sQuote(Sys.getenv("LANGUAGE"))))
          cat(sprintf("locales: %s\n", sQuote(Sys.getlocale())))
          tryCatch(log("a"), error = conditionMessage)
        shell: Rscript {0}

      - name: Check (!Windows)
        if: runner.os != 'Windows'
        run: |
          if (nzchar(Sys.getenv("R_FUTURE_PLAN")) || getRversion() < "3.5.0") Sys.setenv(RCMDCHECK_ERROR_ON = "error")
          rcmdcheck::rcmdcheck(
            build_args = if (getRversion() < "3.5.0") "--no-build-vignettes",
            args = c("--no-manual", "--as-cran", if (getRversion() < "3.5.0") c("--no-vignettes", "--no-build-vignettes", "--ignore-vignettes")),
            check_dir = "check"
          )
        shell: Rscript {0}

      - name: Check (Windows)
        if: runner.os == 'Windows'
        run: |
          rcmdcheck::rcmdcheck(
            args = c("--no-manual", "--as-cran", if (.Platform$OS.type == "windows" && getRversion() >= "4.2.0") "--no-multiarch"),
            check_dir = "check"
          )
        shell: Rscript {0}

      - name: Upload check results
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }}-r${{ matrix.config.r }}-results
          path: check
